// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ITicketHandler is an autogenerated mock type for the ITicketHandler type
type ITicketHandler struct {
	mock.Mock
}

// CreateTicketOption provides a mock function with given fields: c
func (_m *ITicketHandler) CreateTicketOption(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTicket provides a mock function with given fields: c
func (_m *ITicketHandler) GetTicket(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PurchaseFromTicketOption provides a mock function with given fields: c
func (_m *ITicketHandler) PurchaseFromTicketOption(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewITicketHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewITicketHandler creates a new instance of ITicketHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITicketHandler(t mockConstructorTestingTNewITicketHandler) *ITicketHandler {
	mock := &ITicketHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
