// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Samet Avcı",
            "url": "https://www.linkedin.com/in/samet-avci/",
            "email": "sametavc05@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ticket_options": {
            "post": {
                "description": "Create New Ticket Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "POST Create New Ticket Option",
                "parameters": [
                    {
                        "description": "ticket",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.NewTicketDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NewTicketDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/ticket_options/:id": {
            "get": {
                "description": "Get Ticket Option With By ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "GET Get Ticket Option",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetTicketDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/ticket_options/:id/purchases": {
            "post": {
                "description": "Purchase From Ticket Option For Sell Ticket",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "POST Purchase From Ticket Option",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.NewTicketDTO": {
            "type": "object",
            "required": [
                "allocation",
                "name"
            ],
            "properties": {
                "allocation": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.GetTicketDTO": {
            "type": "object",
            "properties": {
                "allocation": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.NewTicketDTO": {
            "type": "object",
            "properties": {
                "allocation": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gowit API Documentation",
	Description:      "This is a server api docs for",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
